name: linux

on:
  pull_request:
    branches: [ "release" ]
  push:
    branches: [ "release" ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: "gcc-10",   cxx: "g++-10",     os: "ubuntu-20.04" }
          - { cc: "clang-10", cxx: "clang++-10", os: "ubuntu-20.04" }

    name: ${{ matrix.compiler.cc }}
    runs-on: ${{ matrix.compiler.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Compiler
        run: |
          if [[ "${{ matrix.compiler.cc }}" == "clang"* ]]; then
            sudo apt-get update
            sudo apt-get install -y ${{ matrix.compiler.cc }}
          else
            sudo apt update
            sudo apt install -y ${{ matrix.compiler.cxx }}
          fi

      - name: Setup dependencies
        run: |
          wget https://ftp.debian.org/debian/pool/main/libu/liburing/liburing1_0.7-3_amd64.deb
          wget https://ftp.debian.org/debian/pool/main/libu/liburing/liburing-dev_0.7-3_amd64.deb
          sudo dpkg -i liburing1_0.7-3_amd64.deb
          sudo dpkg -i liburing-dev_0.7-3_amd64.deb

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                -DINCLUDE_TEST=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Google Test
        working-directory: ${{github.workspace}}/build/test
        run: ./unitTest
